### PR TITLE
Add package.json so we can use via NPM

### PR DESCRIPTION
**Pull request by export-mike**
Added npm package.json to publish to npm registry? 

Are you ok with this?

I've also noticed a conflict in the licencing, you say its MIT but the license is apache... 

i've removed the apache details.

### CODE REVIEW

**Comment by Red-Folder** [comment]
Can you provide details on how this works?

Sorry, very little experience with NPM

**Comment by mikeljames** [comment]
Hey,

sure no problem. Quite simply the package.json file acts a manifest and
source of useful information and even a list of build scripts.

For our use case though we simply want to just use npm to package the
cordova app up onto the npm registry for others to install simply with the
command.

npm install cordova-plugin-bgs-core

I've already gone ahead and published it, under that name as well. I've
used the forked version of this repo.

Publishing simply creates a snapshot of your your code at a point in time.

Users can now specify a version (snapshot) of the code they want to depend
on in their application.

Have you ever used bower? Maven, apt-get? They're all package mangers of
some kind and npm is one that's showing use cases for more than packaging
up just javascript. Which is what makes is pretty bloody awesome.

You can find out a lot more on the npm and node js websites.

https://docs.npmjs.com

Thanks,

Mike

**Comment by Red-Folder** [comment]
Thanks for the info.

I'll have a review once I can get my dev environment to work any sense.

I've been struggling to get Android development working on my various machines for the last 6 months.  Guess its time to have another go at it.

**Comment by Red-Folder** [comment]
Sorry, still struggling with any form of development environment.

In theory I'm ok with the package stuff (as it doesn't effect anything else).

The licence stuff on the other hand; I should probably make sure that I'm using the licences correctly - thus I need to spend some time reviewing.

**Pull request closed without merging**
